global:
  output_dir: "./results"
  enable_rapl: true
  enable_nvml: true
  enable_perf: false
  polling_interval_ms: 10
  cooling_threshold_gpu_c: 50.0
  cooling_threshold_cpu_c: 65.0
  orchestrator_core_isolation: true

experiments:
  - id: "EXP_002_SHARED_MEM_SUM"
    algorithm_path: "algorithms/gpu_single/exp_002_shared_mem_sum"
    
    # "-O3 -use_fast_math", "-G -g", "-lineinfo"
    compiler_flags: "auto"
    
    repetitions: 5000 
    warmup_runs: 5
    
    data:
      sizes: [25000000] 
      
      # ["int32", "int64", "float32", "double"]
      types: ["float32"] 
      
      # "random_uniform" (losowe), "zeros" (same zera), "sequential" (1, 2, 3...)
      generation_mode: "random_uniform" 
      
    hardware:
      # "0", "1", "all"
      gpu_allocation: "all" 
      
      # ["physical_cores_only", "p_cores_only", "e_cores_only", "all"]
      cpu_allocation_strategy: ["physical_cores_only"]
      
      # [true, false]
      use_dedicated_gpu_threads: [false] 
      
      # wielokrotnosci liczby 32 (np. [32, 64, 128, 256, 512, 1024])
      cuda_block_sizes: [256, 512]